import{a as y,S as h,i as n}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g="50254801-91971d45cfc13d9e951cbfc82",b="https://pixabay.com/api/";async function L(i){const t={key:g,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await y.get(b,{params:t})).data}catch{throw new Error("Error fetching data from Pixabay API")}}const d=document.querySelector(".loader"),f=document.querySelector(".gallery");let c=null;function v(){d.classList.remove("visually-hidden")}function l(){d.classList.add("visually-hidden")}function P(){f.innerHTML=""}function S(i){const t=i.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:a,comments:p,downloads:m})=>`<li class="gallery-item">
    <a href="${s}"><img src="${o}" alt="${e}" title=""/></a>
    <div class="cont">
      <p><b>Likes</b><br>${r}</p>
      <p><b>Views</b><br>${a}</p>
      <p><b>Comments</b><br>${p}</p>
      <p><b>Downloads</b><br>${m}</p>
    </div>
</li>`).join("");f.insertAdjacentHTML("beforeend",t),c?c.refresh():c=new h(".gallery a",{captionsData:"alt",captionDelay:250})}const u=document.querySelector("form");u.addEventListener("submit",i=>{i.preventDefault(),P(),v();const t=i.currentTarget.elements["search-text"].value.trim();if(!t)return l(),n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});L(t).then(o=>{if(o.hits.length===0)return n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});S(o.hits)}).catch(o=>{n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).finally(()=>{l(),u.reset()})});
//# sourceMappingURL=index.js.map
