import{a as y,i as n,S as m}from"./assets/vendor-BMHzDZyJ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const p="50254801-91971d45cfc13d9e951cbfc82",h="https://pixabay.com/api/";async function g(i){const t={key:p,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await y.get(h,{params:t})).data}catch{throw new Error("Error fetching data from Pixabay API")}}const d=document.querySelector(".loader"),b=document.querySelector(".gallery");function L(){d.classList.remove("visually-hidden")}function l(){d.classList.add("visually-hidden")}function S(){b.innerHTML=""}function v(i){return i.map(({webformatURL:t,largeImageURL:o,tags:a,likes:e,views:r,comments:s,downloads:f})=>`<li class="gallery-item">
    <a href="${o}"><img src="${t}" alt="${a}" title=""/></a>
    <div class="cont">
      <p><b>Likes</b><br>${e}</p>
      <p><b>Views</b><br>${r}</p>
      <p><b>Comments</b><br>${s}</p>
      <p><b>Downloads</b><br>${f}</p>
    </div>
</li>`).join("")}const u=document.querySelector("form"),P=document.querySelector(".gallery");let c=null;u.addEventListener("submit",i=>{i.preventDefault(),S(),L();const t=i.currentTarget.elements["search-text"].value.trim();if(!t)return l(),n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});g(t).then(o=>{if(o.hits.length===0)return n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});const a=v(o.hits);P.insertAdjacentHTML("beforeend",a),c?c.refresh():c=new m(".gallery a",{captionsData:"alt",captionDelay:250})}).catch(o=>{n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).finally(()=>{l(),u.reset()})});
//# sourceMappingURL=index.js.map
